services:
    gitlab:
        container_name: gitlab
        
        image: gitlab/gitlab-ee:18.8.4-ee.0
        restart: unless-stopped

        hostname: 'gitlab.contoso.com'

        environment:
            TZ: "Asia/Shanghai"

        volumes:
            - '/home/gitlab/config:/etc/gitlab'
            - '/home/gitlab/logs:/var/log/gitlab'
            - '/home/gitlab/data:/var/opt/gitlab'
            - './license_key.pub:/opt/gitlab/embedded/service/gitlab-rails/.license_encryption_key.pub'

        ports:
            - '80:80'
            - '22:22'
        
        shm_size: '16g'


    gitlab-runner1:
        container_name: gitlab-runner-1

        user: 0:0

        image: gitlab/gitlab-runner:v18.8.0
        restart: unless-stopped

        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/home/gitlab-runner:/etc/gitlab-runner'

        environment:
            TZ: "Asia/Shanghai"
